### ISSUE TITLE
Kp values should be divided by 10

### ISSUE THREAD

**Issue by st-bender** [space-physics/geomagindices#2]
Hi,
I believe that the Kp values available from the NOAA ftp site should be divided by 10 before use, to quote ftp://ftp.ngdc.noaa.gov/STP/GEOMAGNETIC_DATA/INDICES/KP_AP/kp_ap.fmt :

    K indices range in 28 steps from 0 (quiet) to 9 (greatly disturbed) with frac-
    tional parts expressed in thirds of a unit.  A K-value equal to 27, for exam-
    ple, means 2 and 2/3 or 3-; a K-value equal to 30 means 3 and 0/3 or 3 exactly;
    and a K-value equal to 33 means 3 and 1/3 or 3+.

Cheers.

**Comment by scivision** [comment]
fixed by https://github.com/space-physics/geomagindices/releases/tag/v1.2.6
