### ISSUE TITLE
Smoothing does not cross year boundaries

### ISSUE THREAD

**Issue by petermao** [space-physics/geomagindices#4]
When [get_indices](https://github.com/space-physics/geomagindices/blob/main/src/geomagindices/base.py#L12) is called, it only considers data from the current year:
https://github.com/space-physics/geomagindices/blob/c989f7df05ac1082f7347cd32cfee7a916e3b30d/src/geomagindices/base.py#L24 https://github.com/space-physics/geomagindices/blob/c989f7df05ac1082f7347cd32cfee7a916e3b30d/src/geomagindices/base.py#L26

The rolling averages (f107 shown here) are labelled on the [right side of the window (see default for `center`)](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.rolling.html), so if `smoothdays` is set to anything greater than 1, then for the first `smoothdays - 1` of the year, `dat["f107s"]` will contain a value using a shorter averaging window than requested.
https://github.com/space-physics/geomagindices/blob/c989f7df05ac1082f7347cd32cfee7a916e3b30d/src/geomagindices/base.py#L32

**Comment by sunipkm** [comment]
I have fixed this issue in my latest commit.

**Comment by petermao** [comment]
Hi Sunip,

thank you for doing this.

Peter
